// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuBzPA6j0Qz0FnZhj38HT_DgM1zl4QCUU',
    appId: '1:1043978903006:web:64ecf125cf9bee426d914f',
    messagingSenderId: '1043978903006',
    projectId: 'neonfirebase-8f69f',
    authDomain: 'neonfirebase-8f69f.firebaseapp.com',
    storageBucket: 'neonfirebase-8f69f.firebasestorage.app',
    measurementId: 'G-VCSLF84JCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr-HZmUgp2EM4ASGqIqq6CXI_wKolXQT8',
    appId: '1:1043978903006:android:585a5ea1d2f86ef06d914f',
    messagingSenderId: '1043978903006',
    projectId: 'neonfirebase-8f69f',
    storageBucket: 'neonfirebase-8f69f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqxCXv3FuW_4uTQM92aCisiPjdJ2uysRY',
    appId: '1:1043978903006:ios:65374f370200a8396d914f',
    messagingSenderId: '1043978903006',
    projectId: 'neonfirebase-8f69f',
    storageBucket: 'neonfirebase-8f69f.firebasestorage.app',
    iosBundleId: 'com.example.neonfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqxCXv3FuW_4uTQM92aCisiPjdJ2uysRY',
    appId: '1:1043978903006:ios:65374f370200a8396d914f',
    messagingSenderId: '1043978903006',
    projectId: 'neonfirebase-8f69f',
    storageBucket: 'neonfirebase-8f69f.firebasestorage.app',
    iosBundleId: 'com.example.neonfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuBzPA6j0Qz0FnZhj38HT_DgM1zl4QCUU',
    appId: '1:1043978903006:web:d35b7e6ce200d1f46d914f',
    messagingSenderId: '1043978903006',
    projectId: 'neonfirebase-8f69f',
    authDomain: 'neonfirebase-8f69f.firebaseapp.com',
    storageBucket: 'neonfirebase-8f69f.firebasestorage.app',
    measurementId: 'G-9EM9PH2YRK',
  );
}
